// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXPUSnMwxtZuc0mDmY-rismeQsEo6mzSI',
    appId: '1:1089906582252:web:6f856cd3c451db62167bc9',
    messagingSenderId: '1089906582252',
    projectId: 'triptaste-b54e8',
    authDomain: 'triptaste-b54e8.firebaseapp.com',
    storageBucket: 'triptaste-b54e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC6WvOX6iUW2AAtM1HXieB2UOzbbzu5A8',
    appId: '1:1089906582252:android:36c8d12a68e802c6167bc9',
    messagingSenderId: '1089906582252',
    projectId: 'triptaste-b54e8',
    storageBucket: 'triptaste-b54e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBegPZtiZ6XGKJzhiAe6XnX98OI_uxvFNg',
    appId: '1:1089906582252:ios:23f4ee6f7dd3575b167bc9',
    messagingSenderId: '1089906582252',
    projectId: 'triptaste-b54e8',
    storageBucket: 'triptaste-b54e8.firebasestorage.app',
    iosClientId: '1089906582252-bltbo9ldaoj9hv5fj0khjq4cqe63khsa.apps.googleusercontent.com',
    iosBundleId: 'com.example.triptasteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBegPZtiZ6XGKJzhiAe6XnX98OI_uxvFNg',
    appId: '1:1089906582252:ios:23f4ee6f7dd3575b167bc9',
    messagingSenderId: '1089906582252',
    projectId: 'triptaste-b54e8',
    storageBucket: 'triptaste-b54e8.firebasestorage.app',
    iosClientId: '1089906582252-bltbo9ldaoj9hv5fj0khjq4cqe63khsa.apps.googleusercontent.com',
    iosBundleId: 'com.example.triptasteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXPUSnMwxtZuc0mDmY-rismeQsEo6mzSI',
    appId: '1:1089906582252:web:9b77fc9789c69fdd167bc9',
    messagingSenderId: '1089906582252',
    projectId: 'triptaste-b54e8',
    authDomain: 'triptaste-b54e8.firebaseapp.com',
    storageBucket: 'triptaste-b54e8.firebasestorage.app',
  );
}
